name: AWS Deployment

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v1 

      # - name: Install dependencies
      #   run: npm install

      # - name: Build project
      #   run: npm run build

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: 'us-east-1'

      # - name: Deploy static website in s3 bucket
      #   uses: aws-actions/elasticbeanstalk-deploy@v1
      #   with:
      #     environment: 'prod'
      #     application-name: 'my-app'
      #     beanstalk-environment-name: 'my-env'

      - name: Deploy to AWS S3
        run: aws s3 sync s3://demo123456789 --delete
